version: '3.8'

services:
  frontend:
    image: ${DOCKERHUB_USERNAME}/euphoria-frontend:latest
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    name: euphoria_default
    external: true 