const textButton =  {
  borderRadius: '20px',
  minWidth: 100,
  border: 'none',
  color: 'rgba(57, 57, 57, 0.7)',
  background: 'none',
  boxShadow: 'none',
  fontWeight: 500,
  fontSize: '15px',
  textTransform: 'none',
  transition: 'color 0.2s',
  '&:hover': {
    color: 'rgba(57, 57, 57, 1)',
    background: 'none',
    border: 'none',
    boxShadow: 'none',
  },
};

export const styles = {
  title: {
    fontSize: '24px',
    fontWeight: '500',
    margin: '10px auto',
    color: '#393939',
  },
  input: {
    backgroundColor: '#ffffff',
    alignItems: 'center',
    width: '400px',
    gap: '20px',
    '& fieldset': {
      borderRadius: '20px',
    },
    '& input, label:not(.MuiInputLabel-shrink)': {
      fontSize: '14px',
    },
  },
  addPhotoIconButton: {
    background: 'none !important',
    boxShadow: 'none',
    padding: '0px',
    '&:hover *, &:active *': {
      background: 'none !important',
      boxShadow: 'none',
    },
    '&:hover img': {
      opacity: 0.7,
    },
    '& img': {
      opacity: 0.4,
      width: '60px',
      height: '60px',
    },
  },
  photoCount: {
    fontSize: '14px',
    color: '#888',
  },
  photoUploadRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: '16px',
    width: '100%',
  },
  photoUploadColumn: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    width: '100%',
    alignItems: 'flex-start',
    marginBottom: '20px',
    '& .ant-upload-list-picture-card': {
      gap: '11.3px !important',
      display: 'flex !important',
      flexWrap: 'wrap',
    },
    //.ant-upload-list-item-container.ant-upload-animate-inline-appear.ant-upload-animate-inline-appear-active.ant-upload-animate-inline
    '& .ant-upload.ant-upload-select, .ant-upload-list-item.ant-upload-list-item-error': {
      borderRadius: '20px !important',
    },
  },
  formColumns: {
    display: 'flex',
    gap: '32px',
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'flex-start',
    minHeight: 0,
    overflow: 'visible',
  },
  formColumn: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '15px',
    minHeight: 0,
    overflow: 'visible',
    height: '100%',
  },
  formColumnCentered: {
    alignItems: 'center',
  },
  hiddenInput: {
    display: 'none',
  },
  datePickerTheme: {
    token: {
      colorPrimary: '#FF5333',
      fontFamily: '"Montserrat Alternates", sans-serif',
      fontStyle: 'normal',
      color: '#393939',
    },
  },
  calendarSmallBox: {
    width: '100%',
    overflow: 'visible',
    '& .ant-picker-calendar': {
      minWidth: '0',
      width: '100%',
      fontSize: '13px',
      borderBottom: '1px solid #E0E0E0',
    },
    '& .ant-picker-calendar-date': {
      height: '50px !important',
      minHeight: '50px !important',
      padding: 0,
      fontSize: '13px',
      lineHeight: 1,
    },
    '& .ant-picker-calendar-date-value': {
      height: '100% !important',
      minHeight: '100% !important',
      lineHeight: 1,
      padding: 0,
      fontSize: '13px',
    },
    '& td.ant-picker-cell': {
      padding: 0,
      minWidth: '24px',
      height: '50px !important',
      lineHeight: 1,
    },
    '& .ant-picker-calendar-header': {
      marginBottom: '4px',
      padding: '0 4px',
    },
    '& .ant-picker-body': {
      padding: '0 4px',
    },
    '& .ant-picker-content th, & .ant-picker-content td': {
      fontSize: '13px',
      padding: '0',
    },
    '& .ant-picker-calendar-date-content': {
      height: '0px !important',
      minHeight: '0px !important',
    },
  },
  stepper: {
    width: '100%',
    maxWidth: 600,
    mb: 3,
  },
  stepContentBox: {
    width: '100%',
    minHeight: 420,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  stepBox: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
  },
  buttonsBox: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    mt: 2,
    width: '100%',
  },
  backButton: textButton,
  deleteAllButton: {
    ...textButton,
    flexGrow: 0,
  },
  datesListBox: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: '0',
    mt: 1,
    maxHeight: '400px',
    overflowY: 'auto',
    flexGrow: 1,
    minHeight: 0,
    justifyContent: 'top',
  },
  noDatesText: {
    color: '#888',
    fontSize: 14,
    textAlign: 'center',
    margin: 'auto',
    mt: 2,
    mb: 2,
  },
  dateListItemBox: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '6px 0',
    '&:hover .removeDateBtn': {
      opacity: 1,
    },
  },
  dateListItemText: {
    fontSize: '15px',
    color: '#393939',
    fontWeight: 400,
    background: 'none',
    padding: 0,
  },
  removeDateBtn: {
    minWidth: 0,
    fontSize: '13px',
    padding: '7px',
    background: 'none',
    boxShadow: 'none',
    opacity: 0.3,
    transition: 'opacity 0.2s',
    '&:hover': {
      background: 'rgba(255,83,51,0.08)',
      opacity: 1,
    },
  },
  dateListDivider: {
    my: 0,
    borderColor: '#eee',
  },
  durationInput: {
    background: '#fff',
    borderRadius: '20px',
    fontSize: '16px',
    fontWeight: 500,
    width: '100%',
    height: '56px',
    paddingLeft: '0',
    paddingRight: '0',
    marginBottom: '20px',
    boxShadow: 'none',
    '& input': {
      fontSize: '16px',
      fontWeight: 600,
      padding: 0,
      textAlign: 'center',
    },
  },
  durationPrefix: {
    color: '#888',
    fontSize: '15px',
    fontWeight: 400,
    marginRight: '8px',
    marginLeft: '12px',
    whiteSpace: 'nowrap',
  },
  durationSuffix: {
    color: '#888',
    fontSize: '15px',
    fontWeight: 400,
    marginLeft: '8px',
    marginRight: '12px',
    whiteSpace: 'nowrap',
  },
  outerContainer: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    width: '100%',
    background: '#fff',
  },
  headerBox: {
    flexShrink: 0,
    padding: '24px 0 0 0',
    background: '#fff',
    zIndex: 2,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
  },
  mainBox: {
    flex: 1,
    minHeight: 0,
    overflow: 'visible',
    width: '100%',
    background: '#fff',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'top',
  },
  footerBox: {
    flexShrink: 0,
    background: '#fff',
    padding: '0px 0 24px 0',
    zIndex: 2,
  },
  datesBox: {
    display: 'flex',
    gap: '10px',
    width: '100%',
    alignItems: 'center',
  },
  saveButton: {
    borderRadius: '15px',
    fontSize: '16px',
    textTransform: 'none',
    fontWeight: '600',
    height: '44px',
    border: '1px solid #FF5333',
    color: '#FF5333',
    background: 'none',
    boxShadow: 'none',
    padding: '10px 20px',
    transition: 'all 0.2s',
    '&:hover': {
      backgroundColor: '#FF5333',
      color: '#fff',
      border: '1px solid #FF5333',
    },
  },
  inputAdaptive: {
    maxWidth: '100%',
    width: '100%',
  },
  autoCompleteTextField: {
    maxWidth: '100%',
    width: '100%',
  },
  mb2: {
    marginBottom: 2,
  },
  removeArrows: {
    '& input::-webkit-outer-spin-button, & input::-webkit-inner-spin-button': {
      '-webkit-appearance': 'none',
      margin: 0,
    },
    '& input[type=number]': {
      '-moz-appearance': 'textfield',
    },
  },
  textFieldContainer: {
    display: 'flex',
    width: '100%',
    maxWidth: '100%',
  },
  textFieldLeft: {
    width: '100%',
    '& input::-webkit-outer-spin-button, & input::-webkit-inner-spin-button': {
      '-webkit-appearance': 'none',
      margin: 0,
    },
    '& input[type=number]': {
      '-moz-appearance': 'textfield',
    },
    '& fieldset': {
      borderRadius: '20px 0px 0px 20px',
      borderRightWidth: '0px',
    },
    '&:hover fieldset': {
      borderRightWidth: '1px',
    },
  },
  textFieldRight: {
    width: '100%',
    '& input::-webkit-outer-spin-button, & input::-webkit-inner-spin-button': {
      '-webkit-appearance': 'none',
      margin: 0,
    },
    '& input[type=number]': {
      '-moz-appearance': 'textfield',
    },
    '& fieldset': {
      borderRadius: '0px 20px 20px 0px',
    },
  },
  descriptionContainer: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    flex: 1,
  },
  formattingButtons: {
    display: 'flex',
    gap: '8px',
    marginBottom: '10px',
    justifyContent: 'center',
    width: '100%',
  },
  formatButton: {
    minWidth: 'auto',
    height: '40px',
    padding: '8px 16px',
    borderRadius: '10px',
    color: '#393939',
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
    textTransform: 'none',
    '&:hover': {
      backgroundColor: 'rgba(57, 57, 57, 0.08)',
    },
    '& .MuiSvgIcon-root': {
      fontSize: '20px',
    },
  },
  descriptionTextField: {
    width: '100%',
    height: '100%',
    flex: 1,
    '& .MuiOutlinedInput-root': {
      height: '100%',
      borderRadius: '20px',
      backgroundColor: '#ffffff',
    },
    '& .MuiOutlinedInput-input': {
      fontSize: '14px',
      height: '100% !important',
    },
  },
}; 