export const POSTS_REQUESTED = 'POSTS_REQUESTED';
export const POSTS_RECEIVED = 'POSTS_RECEIVED';
export const POSTS_FAILED = 'POSTS_FAILED';

export const CHANGE_MODAL_PROPS = 'CHANGE_MODAL_PROPS';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_REQUESTED = 'AUTH_REQUESTED';

export const AUTH_VERIFY_REQUESTED = 'AUTH_VERIFY_REQUESTED';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// Categories
export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const FETCH_TOURS_REQUEST = 'FETCH_TOURS_REQUEST';
export const FETCH_TOURS_SUCCESS = 'FETCH_TOURS_SUCCESS';
export const FETCH_TOURS_FAILURE = 'FETCH_TOURS_FAILURE';

export const FETCH_FOOD_CATEGORIES_REQUEST = 'FETCH_FOOD_CATEGORIES_REQUEST';
export const FETCH_FOOD_CATEGORIES_SUCCESS = 'FETCH_FOOD_CATEGORIES_SUCCESS';
export const FETCH_FOOD_CATEGORIES_FAILURE = 'FETCH_FOOD_CATEGORIES_FAILURE';

export const WHOAMI_REQUEST = 'WHOAMI_REQUEST';
export const WHOAMI_SUCCESS = 'WHOAMI_SUCCESS';
export const WHOAMI_FAILURE = 'WHOAMI_FAILURE';

export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';

export const AUTH_GENERATE_VERIFY_CODE_REQUEST = 'AUTH_GENERATE_VERIFY_CODE_REQUEST';
export const AUTH_GENERATE_VERIFY_CODE_SUCCESS = 'AUTH_GENERATE_VERIFY_CODE_SUCCESS';
export const AUTH_GENERATE_VERIFY_CODE_FAILURE = 'AUTH_GENERATE_VERIFY_CODE_FAILURE';

export const AUTH_VERIFY_EMAIL_REQUEST = 'AUTH_VERIFY_EMAIL_REQUEST';
export const AUTH_VERIFY_EMAIL_SUCCESS = 'AUTH_VERIFY_EMAIL_SUCCESS';
export const AUTH_VERIFY_EMAIL_FAILURE = 'AUTH_VERIFY_EMAIL_FAILURE';
