export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';

export const GET_TOURS_REQUEST = 'GET_TOURS_REQUEST';
export const GET_TOURS_SUCCESS = 'GET_TOURS_SUCCESS';
export const GET_TOURS_FAILURE = 'GET_TOURS_FAILURE';
export const GET_TOUR_REQUEST = 'GET_TOUR_REQUEST';
export const GET_TOUR_SUCCESS = 'GET_TOUR_SUCCESS';
export const GET_TOUR_FAILURE = 'GET_TOUR_FAILURE';

export const SET_TOURS = 'SET_TOURS';
export const SET_TOURS_LOADING = 'SET_TOURS_LOADING';
export const SET_TOURS_ERROR = 'SET_TOURS_ERROR';
export const CREATE_TOUR_REQUEST = 'CREATE_TOUR_REQUEST';
export const CREATE_TOUR_SUCCESS = 'CREATE_TOUR_SUCCESS';
export const CREATE_TOUR_FAILURE = 'CREATE_TOUR_FAILURE';
export const SET_CURRENT_TOUR = 'SET_CURRENT_TOUR';

export const GET_FOOD_CATEGORIES_REQUEST = 'GET_FOOD_CATEGORIES_REQUEST';
export const GET_FOOD_CATEGORIES_SUCCESS = 'GET_FOOD_CATEGORIES_SUCCESS';
export const GET_FOOD_CATEGORIES_FAILURE = 'GET_FOOD_CATEGORIES_FAILURE';

export const WHOAMI_REQUEST = 'WHOAMI_REQUEST';
export const WHOAMI_SUCCESS = 'WHOAMI_SUCCESS';
export const WHOAMI_FAILURE = 'WHOAMI_FAILURE';

export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_GENERATE_VERIFY_CODE_REQUEST = 'AUTH_GENERATE_VERIFY_CODE_REQUEST';
export const AUTH_GENERATE_VERIFY_CODE_SUCCESS = 'AUTH_GENERATE_VERIFY_CODE_SUCCESS';
export const AUTH_GENERATE_VERIFY_CODE_FAILURE = 'AUTH_GENERATE_VERIFY_CODE_FAILURE';

export const AUTH_VERIFY_EMAIL_REQUEST = 'AUTH_VERIFY_EMAIL_REQUEST';
export const AUTH_VERIFY_EMAIL_SUCCESS = 'AUTH_VERIFY_EMAIL_SUCCESS';
export const AUTH_VERIFY_EMAIL_FAILURE = 'AUTH_VERIFY_EMAIL_FAILURE';

export const FETCH_BOOKINGS_REQUEST = 'FETCH_BOOKINGS_REQUEST';
export const FETCH_BOOKINGS_SUCCESS = 'FETCH_BOOKINGS_SUCCESS';
export const FETCH_BOOKINGS_FAILURE = 'FETCH_BOOKINGS_FAILURE';

export const POST_BOOKINGS_REQUEST = 'POST_BOOKINGS_REQUEST';
export const POST_BOOKINGS_SUCCESS = 'POST_BOOKINGS_SUCCESS';
export const POST_BOOKINGS_FAILURE = 'POST_BOOKINGS_FAILURE';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const POST_ORGANIZER_REQUEST = 'POST_ORGANIZER_REQUEST';
export const POST_ORGANIZER_SUCCESS = 'POST_ORGANIZER_SUCCESS';
export const POST_ORGANIZER_FAILURE = 'POST_ORGANIZER_FAILURE';

export const GET_ORGANIZER_STATUS_REQUEST = 'GET_ORGANIZER_STATUS_REQUEST';
export const GET_ORGANIZER_STATUS_SUCCESS = 'GET_ORGANIZER_STATUS_SUCCESS';
export const GET_ORGANIZER_STATUS_FAILURE = 'GET_ORGANIZER_STATUS_FAILURE';
