export const itemStyles = {
  imageListItemBar: {
    background: 'linear-gradient(0deg,rgba(0,0,0,0.9) 0%, rgba(0,0,0,0.5) 25%, rgba(0,0,0,0) 50%)',
    height: '100%',
    alignItems: 'flex-end',
    '& div > div': {
      gap: '40px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      width: '100%',
    },
    '& p': {
      fontFamily: '"Montserrat Alternates", sans-serif',
      fontWeight: 200,
      fontStyle: 'normal',
      fontSize: '24px',
      color: '#fff',
    },
  },
  title: {
    flexGrow: 1,
    overflow: 'hidden',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    textOverflow: 'ellipsis',
    whiteSpace: 'normal',
  },
  verticalDate: {
    position: 'absolute',
    bottom: '70px',
    left: '50%',
    transform: 'translateX(-50%) rotate(-90deg)',
    transformOrigin: 'center',
    whiteSpace: 'nowrap',
    '& p': {
      fontSize: '20px',
      fontWeight: 300,
      color: '#fff',
      lineHeight: 1.2,
    },
  },
  featured: {
    height: '100%',
    width: '100%',
    transition: 'all 1s ease',
    position: 'relative',
    overflow: 'hidden',
    borderRadius: '25px',
    '& img': {
      objectFit: 'cover',
      height: '100%',
      width: '100%',
    },
  },
  default: {
    height: '100%',
    width: '126px',
    transition: 'all 1s ease',
    position: 'relative',
    overflow: 'hidden',
    borderRadius: '25px',
    '& img': {
      objectFit: 'cover',
      height: '100%',
      width: '100%',
    },
  },
};
