name: Deploy to Production

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: denvill/euphoria-frontend
        build-args: |
          VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: 62.109.17.167
        username: root
        key: ${{ secrets.EUPHORIA_DEPLOY_KEY }}
        script: |
          cd /root
          rm -rf euphoria-frontend
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.EUPHORIA_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -v git@github.com
          git clone git@github.com:mariasol/euphoria-frontend.git euphoria-frontend
          cd euphoria-frontend
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" > .env
          docker-compose -f docker-compose.frontend.yml pull
          docker-compose -f docker-compose.frontend.yml up -d 